repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
    -   id: ruff-format
    -   id: ruff-check
        args: [--fix]
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.4.0
    hooks:
    -   id: eslint
        files: frontend/.*\.(js|ts|jsx|tsx)$
        args: [--fix]
