services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app/
          ignore:
            - .venv/
        - action: rebuild
          path: ./backend/pyproject.toml
    command:
    - /app/backend/scripts/dev-server.sh
    ports:
      - "127.0.0.1:9933:8000"
    environment:
      - DATABASE_URL=postgresql://lexigrok:NOTPRODcf5962655799c65cf8bf3e811691b@db:5432/lexigrok
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      - db
      - minio

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=lexigrok
      - POSTGRES_PASSWORD=NOTPRODcf5962655799c65cf8bf3e811691b
      - POSTGRES_DB=lexigrok
    ports:
      - "127.0.0.1:25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "127.0.0.1:29000:9000"
      - "127.0.0.1:29001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data:
